services:
  app:
    build: .
    ports: 
      - 3000:3000
    volumes:
      - .:/home/node/app

  db: 
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    ports:
      - "3306:3306"

    # create a path to store the data
    # dont commit this to git =)
    #volumes:
     # - ./.docker/dbdata:/var/lib/mysql